apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio
spec:
  selector:
    matchLabels:
      app: personal-portfolio
  template:
    metadata:
      labels:
        app: personal-portfolio
    spec:
      containers:
      - name: personal-portfolio
        image: "${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:latest" #placeholder
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "450Mi"
            cpu: "400m"
        ports:
        - containerPort: 80
