on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker system prune -a
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG} -f ./Dockerfile . --no-cache
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Configure kubeconfig and deploy to kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        echo "${{ github.run_number }}"
        kubectl set image deployment/personal-portfolio personal-portfolio=40075793/personal-website2:${{ github.run_number }}

    # - name: Deploy to Kubernetes (Set Image)
    #   run: |
    #     kubectl set image deployment/personal-portfolio personal-portfolio=40075793/personal-portfolio-image:${{ github.run_number }}

    - name: Clean up kubeconfig
      run: |
        rm -f kubeconfig.yaml
