on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build_and_push  # Add an ID to the step for outputs
      run: |
        IMAGE_TAG=${{ github.run_number }}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:$IMAGE_TAG -f ./Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:$IMAGE_TAG

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl get all

    - name: Deploy to Kubernetes (Set Image)
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}  # Use the shared environment variable
      run: |
        kubectl set image deployment/personal-portfolio personal-portfolio=${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:$IMAGE_TAG

    - name: Clean up kubeconfig
      run: |
        rm -f kubeconfig.yaml
