on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG} -f ./Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG}
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl get all
    
    - name: Deploy to Kubernetes
      run: |
        # Update the deployment file with the latest image tag
        sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG}|g" ./kubernetes/deployment.yaml
        kubectl apply -f ./kubernetes/deployment.yaml

    - name: Clean up kubeconfig
      run: |
        rm -f kubeconfig.yaml


