on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: ls
      run: ls
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd 
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio-image:${IMAGE_TAG}

